name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y libx11-dev xserver-xorg-video-dummy xserver-xorg-core xserver-xephyr xterm xvfb
    - name: Build
      run: make
    - name: Test in Xephyr
      run: |
        # Start virtual display server
        Xvfb :99 -screen 0 1024x768x24 &
        sleep 2
        export DISPLAY=:99

        # Start nested X server (Xephyr)
        Xephyr -ac -br -noreset -screen 800x600 :1 &
        sleep 2

        # Run window manager in nested display
        export DISPLAY=:1
        ./sWM &
        sleep 3

        # Test with xterm
        xterm -hold -e "echo 'Xephyr test successful'; sleep 3" &
        sleep 10
